export enum AppointmentTypeEnum {

    RETORNO                     = 'RETORNO',                     
    CONSULTA_URGENCIA           = 'CONSULTA_URGENCIA',           
    PRIMEIRA_CONSULTA           = 'PRIMEIRA_CONSULTA',           
    CONSULTA_ROTINA             = 'CONSULTA_ROTINA',             
    CONSULTA_PREVENTIVA         = 'CONSULTA_PREVENTIVA',         
    CHECKUP_EXECUTIVO           = 'CHECKUP_EXECUTIVO',           
    TELEATENDIMENTO             = 'TELEATENDIMENTO',
    
    CONSULTA_PEDIATRICA         = 'CONSULTA_PEDIATRICA',         
    CONSULTA_GERIATRICA         = 'CONSULTA_GERIATRICA',         
    CONSULTA_PRENATAL           = 'CONSULTA_PRENATAL',           
    CONSULTA_PSIQUIATRICA       = 'CONSULTA_PSIQUIATRICA',       
    CONSULTA_NUTRICIONAL        = 'CONSULTA_NUTRICIONAL',        
    CONSULTA_FISIOTERAPIA       = 'CONSULTA_FISIOTERAPIA',       
    CONSULTA_ODONTOLOGICA       = 'CONSULTA_ODONTOLOGICA',
    
    CONSULTA_PRE_OPERATORIA     = 'CONSULTA_PRE_OPERATORIA',     
    CONSULTA_POS_OPERATORIA     = 'CONSULTA_POS_OPERATORIA',     
    CONSULTA_RESULTADO_EXAMES   = 'CONSULTA_RESULTADO_EXAMES',   
    CONSULTA_PLANEJAMENTO_FAM   = 'CONSULTA_PLANEJAMENTO_FAM',   
    CRESCIMENTO_DESENVOLVIMENTO = 'CRESCIMENTO_DESENVOLVIMENTO',
    
    USG_ABDOMINAL               = 'USG_ABDOMINAL',               
    USG_OBSTETRICA              = 'USG_OBSTETRICA',              
    USG_TRANSVAGINAL            = 'USG_TRANSVAGINAL',            
    USG_MORFOLOGICA             = 'USG_MORFOLOGICA',             
    USG_MAMARIA                 = 'USG_MAMARIA',                 
    MAMOGRAFIA                  = 'MAMOGRAFIA',                  
    RAIO_X                      = 'RAIO_X',                      
    TOMOGRAFIA                  = 'TOMOGRAFIA',                  
    RESSONANCIA_MAGNETICA       = 'RESSONANCIA_MAGNETICA',       
    DENSITOMETRIA_OSSEA         = 'DENSITOMETRIA_OSSEA',         
    CINTILOGRAFIA               = 'CINTILOGRAFIA',               
    PET_CT                      = 'PET_CT',
    
    ELETROCARDIOGRAMA           = 'ELETROCARDIOGRAMA',           
    ECOCARDIOGRAMA              = 'ECOCARDIOGRAMA',              
    HOLTER                      = 'HOLTER',                      
    MAPA                        = 'MAPA',                        
    TESTE_ESFORCO               = 'TESTE_ESFORCO',               
    CATETERISMO                 = 'CATETERISMO',                 
    
    ENDOSCOPIA                  = 'ENDOSCOPIA',                  
    COLONOSCOPIA                = 'COLONOSCOPIA',                
    COLPOSCOPIA                 = 'COLPOSCOPIA',                 
    RETOSSIGMOIDOSCOPIA         = 'RETOSSIGMOIDOSCOPIA',         
    
    ELETROENCEFALOGRAMA         = 'ELETROENCEFALOGRAMA',         
    ELETROMIOGRAFIA             = 'ELETROMIOGRAFIA',             
    POTENCIAL_EVOCADO           = 'POTENCIAL_EVOCADO',           
    
    ESPIROMETRIA                = 'ESPIROMETRIA',                
    POLIGRAFIA_SONO             = 'POLIGRAFIA_SONO',             
    
    COLETA_LABORATORIAL         = 'COLETA_LABORATORIAL',         
    CURVA_GLICEMICA             = 'CURVA_GLICEMICA',
    PREVENTIVO_PAPANICOLAU      = 'PREVENTIVO_PAPANICOLAU',      
    BIOPSIA                     = 'BIOPSIA',                     
    TESTE_ALERGIA               = 'TESTE_ALERGIA',               
    
    VACINACAO                   = 'VACINACAO',                   
    CURATIVO                    = 'CURATIVO',                    
    INFILTRACAO                 = 'INFILTRACAO',                 
    RETIRADA_PONTOS             = 'RETIRADA_PONTOS',             
    INALACAO                    = 'INALACAO',                    
    DRENAGEM                    = 'DRENAGEM',                    
    CAUTERIZACAO                = 'CAUTERIZACAO',
    PEQUENA_CIRURGIA            = 'PEQUENA_CIRURGIA',
    APLICACAO_MEDICAMENTO       = 'APLICACAO_MEDICAMENTO',
  
    OUTRO                       = 'OUTRO',
  }
  
  export const APPOINTMENT_DEFAULT_DURATIONS: Record<AppointmentTypeEnum, number> = {
    [AppointmentTypeEnum.PRIMEIRA_CONSULTA]:           60,
    [AppointmentTypeEnum.RETORNO]:                     30,
    [AppointmentTypeEnum.CONSULTA_URGENCIA]:           20,
    [AppointmentTypeEnum.CONSULTA_ROTINA]:             40,
    [AppointmentTypeEnum.CONSULTA_PREVENTIVA]:         40,
    [AppointmentTypeEnum.CHECKUP_EXECUTIVO]:           90,
    [AppointmentTypeEnum.TELEATENDIMENTO]:             30,
    [AppointmentTypeEnum.CONSULTA_PEDIATRICA]:         45,
    [AppointmentTypeEnum.CONSULTA_GERIATRICA]:         60,
    [AppointmentTypeEnum.CONSULTA_PRENATAL]:           30,
    [AppointmentTypeEnum.CONSULTA_PSIQUIATRICA]:       60,
    [AppointmentTypeEnum.CONSULTA_NUTRICIONAL]:        45,
    [AppointmentTypeEnum.CONSULTA_FISIOTERAPIA]:       50,
    [AppointmentTypeEnum.CONSULTA_ODONTOLOGICA]:       45,
    [AppointmentTypeEnum.CONSULTA_PRE_OPERATORIA]:     45,
    [AppointmentTypeEnum.CONSULTA_POS_OPERATORIA]:     30,
    [AppointmentTypeEnum.CONSULTA_RESULTADO_EXAMES]:   30,
    [AppointmentTypeEnum.CONSULTA_PLANEJAMENTO_FAM]:   45,
    [AppointmentTypeEnum.CRESCIMENTO_DESENVOLVIMENTO]: 40,
    [AppointmentTypeEnum.USG_ABDOMINAL]:               30,
    [AppointmentTypeEnum.USG_OBSTETRICA]:              30,
    [AppointmentTypeEnum.USG_TRANSVAGINAL]:            20,
    [AppointmentTypeEnum.USG_MORFOLOGICA]:             60,
    [AppointmentTypeEnum.USG_MAMARIA]:                 25,
    [AppointmentTypeEnum.MAMOGRAFIA]:                  20,
    [AppointmentTypeEnum.RAIO_X]:                      15,
    [AppointmentTypeEnum.TOMOGRAFIA]:                  30,
    [AppointmentTypeEnum.RESSONANCIA_MAGNETICA]:       60,
    [AppointmentTypeEnum.DENSITOMETRIA_OSSEA]:         20,
    [AppointmentTypeEnum.CINTILOGRAFIA]:               90,
    [AppointmentTypeEnum.PET_CT]:                      120,
    [AppointmentTypeEnum.ELETROCARDIOGRAMA]:           20,
    [AppointmentTypeEnum.ECOCARDIOGRAMA]:              45,
    [AppointmentTypeEnum.HOLTER]:                      20,
    [AppointmentTypeEnum.MAPA]:                        15,
    [AppointmentTypeEnum.TESTE_ESFORCO]:               45,
    [AppointmentTypeEnum.CATETERISMO]:                 90,
    [AppointmentTypeEnum.ENDOSCOPIA]:                  30,
    [AppointmentTypeEnum.COLONOSCOPIA]:                45,
    [AppointmentTypeEnum.COLPOSCOPIA]:                 30,
    [AppointmentTypeEnum.RETOSSIGMOIDOSCOPIA]:         30,
    [AppointmentTypeEnum.ELETROENCEFALOGRAMA]:         60,
    [AppointmentTypeEnum.ELETROMIOGRAFIA]:             60,
    [AppointmentTypeEnum.POTENCIAL_EVOCADO]:           60,
    [AppointmentTypeEnum.ESPIROMETRIA]:                30,
    [AppointmentTypeEnum.POLIGRAFIA_SONO]:             30,
    [AppointmentTypeEnum.COLETA_LABORATORIAL]:         15,
    [AppointmentTypeEnum.CURVA_GLICEMICA]:             120,
    [AppointmentTypeEnum.PREVENTIVO_PAPANICOLAU]:      20,
    [AppointmentTypeEnum.BIOPSIA]:                     30,
    [AppointmentTypeEnum.TESTE_ALERGIA]:               40,
    [AppointmentTypeEnum.VACINACAO]:                   15,
    [AppointmentTypeEnum.CURATIVO]:                    20,
    [AppointmentTypeEnum.INFILTRACAO]:                 20,
    [AppointmentTypeEnum.RETIRADA_PONTOS]:             15,
    [AppointmentTypeEnum.INALACAO]:                    30,
    [AppointmentTypeEnum.DRENAGEM]:                    30,
    [AppointmentTypeEnum.CAUTERIZACAO]:                20,
    [AppointmentTypeEnum.PEQUENA_CIRURGIA]:            60,
    [AppointmentTypeEnum.APLICACAO_MEDICAMENTO]:       15,
    [AppointmentTypeEnum.OUTRO]:                       30,
  };